### ISSUE TITLE
Error when parse  lego.parse('[\S]') or similar regex

### ISSUE THREAD

**Issue by uynil** [qntm/greenery#35]
When I parse regex like [\S], it will give error like
``` python
>>> lego.parse('[\S\s]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yyy/.pyenv/versions/xx/lib/python3.6/site-packages/greenery/lego.py", line 68, in parse
    return pattern.parse(string)
  File "/Users/yy/.pyenv/versions/xx/lib/python3.6/site-packages/greenery/lego.py", line 244, in parse
    raise Exception("Could not parse '" + string + "' beyond index " + str(i))
Exception: Could not parse '[\S\s]' beyond index 0
```

**Comment by qntm** [comment]
Yeah, negated shorthands `\D`, `\W` and `\S` are not recognised inside a charclass. This would have been fiddly but maybe I'll implement it sometime. Fortunately there is a trivial workaround, instead of writing `[\S]` just write `[^\s]` or `\S`, and instead of writing `[\S\s]` just write `.`. If you have something more complex like `[\Wdef]`, render it as `\W|[def]` and then do what `greenery` is designed to do:

```
>>> from greenery import lego
>>> str(lego.parse('\\W|[def]').reduce())
'[^0-9A-Z_abcg-z]'
```
