### ISSUE TITLE
More efficient way to evaluate empty intersections?

### ISSUE THREAD

**Issue by neelsomani** [qntm/greenery#45]
Hey, not sure if this is possible, but the computation takes a really long time for expressions with wildcards at the beginning and end.

Is there some way to stop the computation early when computing the intersection if we identify that it's non-empty (rather than computing the full intersection)? Thanks!

Edit: Noticing that it only seems takes a while for expressions where I see there is certainly a non-empty intersection. Is it safe to assume that if the intersection takes more than maybe 30 seconds to compute then it's not empty?

**Comment by qntm** [comment]
It depends what you mean by "wildcards". If the regular expressions are `.*X.*` and `.*Y.*` then there will *always* be an intersection no matter what `X` or `Y` are, because you can just have `XY`. (As is mentioned in the README, trying to compute the intersection in this case doesn't generally produce legible results.)

If you're looking at something more complicated, then I think it becomes a little trickier. `greenery` computes intersections using a series of steps:

1. convert regexes to FSMs
2. compute intersection of FSMs as a new FSM
3. convert FSM back into regex

The first step is usually relatively fast. The second step may or may not be fast, but the third step can be very slow I think. You might be able to productively skip that step. Here's the code for the regex intersection method:

```python
	def intersection(self, other):
		alphabet = self.alphabet() | other.alphabet()
		combined = self.to_fsm(alphabet) & other.to_fsm(alphabet)
		return from_fsm(combined)
```

You may just want to extract those first two lines.

```python
regex1 = lego.parse('abc...')
regex2 = lego.parse('...def')
alphabet = regex1.alphabet() | regex2.alphabet()
fsm1 = regex1.to_fsm(alphabet)
fsm2 = regex2.to_fsm(alphabet)
fsm3 = fsm1 & fsm2

# Then...
print(not fsm3.empty())
```

If that's no good to you either then we might be looking at extracting more code from the guts of the FSM intersection method, so that it can exit early as soon as it detects the existence of a final state.

**Comment by neelsomani** [comment]
Perfect, thank you! Exactly what I was looking for. Works great.
