### ISSUE TITLE
Why are instance attributes initialized with `self.__dict__`?

### ISSUE THREAD

**Issue by Seanny123** [qntm/greenery#56]
Less of an issue, more of a curiosity.

In all the class `__init__(self)` methods, there is something like:
```python
self.__dict__["chars"]   = chars
self.__dict__["negated"] = negateMe
```

Instead of:
```python
self.chars   = chars
self.negated = negateMe
```

This breaks static checks, but since this is mostly your repository I don't think that's a problem. However, I am curious __why__ you initialize attributes this way. Does it give some special functionality that I missed?

**Comment by qntm** [comment]
This is going back a way, but I believe my objective was to make it so that the objects created by `greenery` were immutable - to prevent consumers from making manual changes to `obj.chars` or `obj.negated`. There are probably better ways of achieving the same result that I wasn't aware of at the time.

**Comment by Seanny123** [comment]
FYI, the modern (Python 3.7) approach seems to be marking a class with [`@dataclass(frozen=True)`](https://docs.python.org/3/library/dataclasses.html#frozen-instances).

To be clear, I do not expect you to make these changes to the code base! If you're curious about how this would look, I can make an Merge Request.

**Comment by qntm** [comment]
If you opened a PR which made that change, I would probably respond positively 👍
