### ISSUE TITLE
greedy vs non-greedy, which is default?

### ISSUE THREAD

**Issue by aha79** [qntm/greenery#94]
In the readme there is the sentence 

> The greedy operators *?, +?, ?? and {m,n}? are not supported, since they do not alter the regular language.

As far as I know, in regex context the operators with ? are the non-greedy operations (https://stackoverflow.com/a/34806154/1739884) and the operatos (*, + and ?) are the greedy ones.
This seems to be a contradiction.

So what does the sentence mean?  There are two options:

 1. Is it that the **non-greedy** operators (*?, +, ?) are not supported, or
 2. That the greedy operators (*, +, ?) are not supported (and that *?, +? and ?? is what greenery implementes)?
 
 If it is 2., my question would be if the greedy operators are really regular in the computer science sense?
Example:  The greedy regular expression `A.*Z`  would accept "AxZ", "AZ" and "AZZ", but the non-greedy `A.*?Z` will accept "AxZ" and "AZ" but not "AZZ". So greedy uses some kind of backtracking (https://stackoverflow.com/questions/5319840/greedy-vs-reluctant-vs-possessive-qualifiers) not sure if this makes the regex "regular"

**Comment by qntm** [comment]
In the context of `greenery`, all regular expressions are implicitly anchored at the start and end of the input string. The regular expression `^A.*?Z$` will indeed match the full three-character string "AZZ".

However, yes, there is a typo in the README. I'll fix that, thank you.

**Comment by aha79** [comment]
Ah, ok. Thank you. So it is actually case 1).

Could elaborate a bit on the ", since they do not alter the regular language." 
What exactly does this mean?

Are you saying that since greenery anchors the regex implicitly at start and end, there is no difference between greedy regex and non-greedy ? In other words `.*` and `.*?` in a regex with `^` and `$` behave the same?

**Comment by qntm** [comment]
Yes. A regular language is a set of strings, and a regular expression is a very concise descriptor for that set. Changing from a `^.*$` to a `^.*?$` does not alter the set of strings - the sets are the same, so these two regular expressions describe the same regular language.

What does change is the *matching behaviour* - which substrings might be pulled out of the input string as matches. However, `greenery` generally is not concerned with matching behaviour, mainly because preserving matching behaviour after computing the intersection of two regular expressions is impossible.

Well, very difficult. I don't know. I may look into that sometime. But for now `greenery` just returns a Boolean expressing set membership. Yes, the input string is part of this regular language, or no, it isn't.

**Comment by aha79** [comment]
I see, thank you. So greedy vs non-greedy only affects matching behavior, not the whole set of strings the regex matches. 
This I was not aware of.

So for greenery purposes (logical operations, logical testing with regexes) we can simply assume *? +? and ?? are the same as * + and ?. Maybe I was confused by the words "is not supported" in the readme, incorrectly assuming that the non-greedy regexes cannot be handled by  greenery. In fact they can, it is just the **parsing** that does not recognize the non-greedy variants.

This is fine for me, as I have written my own regex parser and construct a greenery pattern object myself. (I need to support ecma262 regexes)
